language: scala

scala:
   - 2.12.9
   - 2.13.0
   - 2.11.12

jdk:
   - openjdk8


cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier

script:
  - sbt ++$TRAVIS_SCALA_VERSION test


